#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

process_game() {
    compress_audio
    mv "data.win" "game.droid"
    # Final completion message
    echo "Patching process complete!"
}

compress_audio() {
    # Compress audio
        echo "Compressing audio. The process will take 5-10 minutes."     
        mkdir -p "$TMPDIR"
        # Run the compression tool
        echo "Running gmKtool.py with parameters..."
        PYTHON=$(which python3)
        $PYTHON ./tools/gmKtool.py -vvv -m 1024 -b 64 -d "$TMPDIR" "$GAMEDIR/data.win"

        if [ $? -eq 0 ]; then
            echo "Compression completed successfully."
            mv "$TMPDIR/"* "$GAMEDIR"
            echo "Moved compressed files to $GAMEDIR."
            rmdir "$TMPDIR"
            echo "Temporary directory $TMPDIR removed."
            echo "Audio compression applied successfully."
        else
            echo "Audio compression failed."
            echo "Cleaning up temporary directory $TMPDIR."
            rm -rf "$TMPDIR"
        fi
}

# Call the function
process_game
